/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blood.bank.database.project;

/**
 *
 * @author user
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form AllPageHome
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SearchDonor = new javax.swing.JButton();
        BloodBankStock = new javax.swing.JButton();
        AddDonorInformation = new javax.swing.JButton();
        DeleteDonorInformation = new javax.swing.JButton();
        UpdateDonorInformation = new javax.swing.JButton();
        ShowAllDonor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("*Welcome To Admin Panel*");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 400, 39));

        SearchDonor.setBackground(new java.awt.Color(204, 51, 0));
        SearchDonor.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        SearchDonor.setForeground(new java.awt.Color(255, 255, 255));
        SearchDonor.setText("Search Donor");
        SearchDonor.setBorder(null);
        SearchDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDonorActionPerformed(evt);
            }
        });
        getContentPane().add(SearchDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 213, 35));

        BloodBankStock.setBackground(new java.awt.Color(204, 51, 0));
        BloodBankStock.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        BloodBankStock.setForeground(new java.awt.Color(255, 255, 255));
        BloodBankStock.setText("Blood Bank Stock");
        BloodBankStock.setBorder(null);
        BloodBankStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodBankStockActionPerformed(evt);
            }
        });
        getContentPane().add(BloodBankStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 213, 41));

        AddDonorInformation.setBackground(new java.awt.Color(204, 51, 0));
        AddDonorInformation.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        AddDonorInformation.setForeground(new java.awt.Color(255, 255, 255));
        AddDonorInformation.setText("Add Donor Information");
        AddDonorInformation.setBorder(null);
        AddDonorInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDonorInformationActionPerformed(evt);
            }
        });
        getContentPane().add(AddDonorInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 213, 40));

        DeleteDonorInformation.setBackground(new java.awt.Color(204, 51, 0));
        DeleteDonorInformation.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        DeleteDonorInformation.setForeground(new java.awt.Color(255, 255, 255));
        DeleteDonorInformation.setText("Delete Donor Information");
        DeleteDonorInformation.setBorder(null);
        DeleteDonorInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDonorInformationActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteDonorInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 213, 38));

        UpdateDonorInformation.setBackground(new java.awt.Color(204, 51, 0));
        UpdateDonorInformation.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        UpdateDonorInformation.setForeground(new java.awt.Color(255, 255, 255));
        UpdateDonorInformation.setText("Update Donor Information");
        UpdateDonorInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDonorInformationActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateDonorInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, 39));

        ShowAllDonor.setBackground(new java.awt.Color(204, 51, 0));
        ShowAllDonor.setFont(new java.awt.Font("Arial", 3, 15)); // NOI18N
        ShowAllDonor.setForeground(new java.awt.Color(255, 255, 255));
        ShowAllDonor.setText("Show All Donor Details");
        ShowAllDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllDonorActionPerformed(evt);
            }
        });
        getContentPane().add(ShowAllDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 213, 37));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood/bank/database/project/zAdmin.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 1160, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateDonorInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDonorInformationActionPerformed
        UpdateDonorDetails y = new UpdateDonorDetails();
        y.show();
        dispose();
    }//GEN-LAST:event_UpdateDonorInformationActionPerformed

    private void ShowAllDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllDonorActionPerformed
        AllDonorDetails x = new AllDonorDetails();
        x.show();
        dispose();
        
    }//GEN-LAST:event_ShowAllDonorActionPerformed

    private void SearchDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDonorActionPerformed
        SearchSubPage ssp = new SearchSubPage();
        
        ssp.show();
        dispose();
    }//GEN-LAST:event_SearchDonorActionPerformed

    private void BloodBankStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodBankStockActionPerformed
        StockSubPage s = new StockSubPage();
        s.show();
        dispose();
    }//GEN-LAST:event_BloodBankStockActionPerformed

    private void AddDonorInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDonorInformationActionPerformed
       
        
        
        AddNewDonor a = new AddNewDonor();
        a.show();
        dispose();
    }//GEN-LAST:event_AddDonorInformationActionPerformed

    private void DeleteDonorInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDonorInformationActionPerformed
        DeleteDonor a = new DeleteDonor();
        a.show();
        dispose();
    }//GEN-LAST:event_DeleteDonorInformationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDonorInformation;
    private javax.swing.JButton BloodBankStock;
    private javax.swing.JButton DeleteDonorInformation;
    private javax.swing.JButton SearchDonor;
    private javax.swing.JButton ShowAllDonor;
    private javax.swing.JButton UpdateDonorInformation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
